std = "roblox"

[rules]
empty_if = "warn"
if_same_then_else = "warn"
local_used_instead_of_local = "warn"
multiple_statements = "allow"
shadowing = "allow"
undefined_variable = "warn"
unused_variable = "warn"
unbalanced_assignments = "warn"
unbalanced_returns = "warn"
trailing_whitespace = "warn"
comparison_type = "warn"
constant_table_index = "warn"
deprecated = "warn"
empty_loop = "warn"
global_mutating = "warn"
global_used_as_local = "warn"
mismatched_arg_count = "warn"
mixed_equal = "warn"
mixed_tables = "warn"
must_index = "warn"
no_local = "warn"
roblox_incorrect_property_declaration = "warn"
suspicious_string = "warn"
unnecessary_string_concatenation = "warn"
unreachable_code = "warn"